### ISSUE TITLE
BumZ Bilder

### ISSUE THREAD

**Issue by TheKrex** [skyfrk/my-website#2]
Kinguin
https://www.google.com/imgres?imgurl=https%3A%2F%2Fvignette.wikia.nocookie.net%2Fcswikia%2Fimages%2Fd%2Fd6%2FSteam_logo_2014.png%2Frevision%2Flatest%3Fcb%3D20140910122059&imgrefurl=http%3A%2F%2Fcounterstrike.wikia.com%2Fwiki%2FSteam&docid=wRqr3rIPh-BeKM&tbnid=6mIU-ORk2WDCnM%3A&vet=10ahUKEwiS4qT29O3eAhUSyoUKHcS3BNwQMwhrKAIwAg..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=steam&ved=0ahUKEwiS4qT29O3eAhUSyoUKHcS3BNwQMwhrKAIwAg&iact=mrc&uact=8
--------------
Humble
https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.linuxjournal.com%2Ffiles%2Flinuxjournal.com%2Fufiles%2Fimagecache%2Flarge-550px-centered%2Fu1000009%2Fbindle-square-red-transparent.png&imgrefurl=https%3A%2F%2Fwww.linuxjournal.com%2Fcontent%2Fhumble-hacker&docid=saCxleDuThSvzM&tbnid=1JSZcWegetxRmM%3A&vet=10ahUKEwiOoLm19O3eAhVK4YUKHXqeDUoQMwhsKAEwAQ..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=humble%20bundle%2B%23&ved=0ahUKEwiOoLm19O3eAhVK4YUKHXqeDUoQMwhsKAEwAQ&iact=mrc&uact=8
---------------
W2G
https://www.google.com/imgres?imgurl=https%3A%2F%2Fd2.alternativeto.net%2Fdist%2Ficons%2Fwatch2gether_76380.png%3Fwidth%3D128%26height%3D128%26mode%3Dcrop%26upscale%3Dfalse&imgrefurl=https%3A%2F%2Falternativeto.net%2Fsoftware%2Fwatch2gether%2F&docid=Eg5H0SzPdiYONM&tbnid=YdTFJgYShoAlYM%3A&vet=10ahUKEwj0gu-78-3eAhUKQRoKHSR6DNMQMwg8KAEwAQ..i&w=128&h=128&client=firefox-b&bih=966&biw=1920&q=%20Watch2Gether&ved=0ahUKEwj0gu-78-3eAhUKQRoKHSR6DNMQMwg8KAEwAQ&iact=mrc&uact=8
---------------
CS Stash
https://www.google.com/imgres?imgurl=https%3A%2F%2Fsteamcommunity-a.akamaihd.net%2Feconomy%2Fimage%2F-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsRVx4MwFo5_T3eAQ3i6DMIW0X7ojiwoHax6egMOKGxj4G68Nz3-jCp4itjFWx-ktqfSmtcwqVx6sT%2F256fx256f&imgrefurl=https%3A%2F%2Fitemdb.opskins.com%2Fcase%2FCS-GO-Weapon-Case&docid=LJ2FAb0ljWOY2M&tbnid=opiIEh3zG9wtpM%3A&vet=12ahUKEwjZmZyj8-3eAhVQJhoKHej4B6A4ZBAzKAkwCXoECAEQCg..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=csgo%20skins&ved=2ahUKEwjZmZyj8-3eAhVQJhoKHej4B6A4ZBAzKAkwCXoECAEQCg&iact=mrc&uact=8
---------------
Twitch
https://www.google.com/imgres?imgurl=https%3A%2F%2Fvignette.wikia.nocookie.net%2Fmiscreated%2Fimages%2F4%2F43%2FTwitch_icon.png%2Frevision%2Flatest%3Fcb%3D20150421182441&imgrefurl=http%3A%2F%2Fmiscreated.wikia.com%2Fwiki%2FFile%3ATwitch_icon.png&docid=mIRmVfQwSjtB2M&tbnid=mmSkMIvZ119j0M%3A&vet=10ahUKEwjh69es8u3eAhUH1xoKHc9tCmYQMwhqKAIwAg..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=twitch&ved=0ahUKEwjh69es8u3eAhUH1xoKHc9tCmYQMwhqKAIwAg&iact=mrc&uact=8
-----
Kinguin (ohne Schriftzug bitte)
https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn6.aptoide.com%2Fimgs%2F6%2Fe%2Fa%2F6ea2456377da2614ed60178cc063b26e_icon.jpg%3Fw%3D256&imgrefurl=https%3A%2F%2Fkinguin.en.aptoide.com%2F%3Fthreads_filter%3Den%26language_change%3D1&docid=Lb_cPSIIKz35tM&tbnid=Kl-9hP_kdsIf_M%3A&vet=10ahUKEwjZtdGV9e3eAhWxxIUKHbh1B0YQMwhAKAIwAg..i&w=256&h=256&itg=1&client=firefox-b&bih=966&biw=1920&q=kinguin%20icon&ved=0ahUKEwjZtdGV9e3eAhWxxIUKHbh1B0YQMwhAKAIwAg&iact=mrc&uact=8
---------------
GtA Events
https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.iconverticons.com%2Ffiles%2Fico%2F9feca6582f22e9a7.ico%3Fdownload%3Dtrue&imgrefurl=https%3A%2F%2Ficonverticons.com%2Ficons%2F9feca6582f22e9a7%2F&docid=m2z7-zs0fwIloM&tbnid=J2FEeL3lLIPzfM%3A&vet=10ahUKEwih6tqG8e3eAhUPJBoKHaN5CZEQMwg3KAAwAA..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=gta%20online%20icon&ved=0ahUKEwih6tqG8e3eAhUPJBoKHaN5CZEQMwg3KAAwAA&iact=mrc&uact=8
-------------------
Amazon
https://www.google.com/imgres?imgurl=http%3A%2F%2Faux.iconspalace.com%2Fuploads%2Famazon-icon-256.png&imgrefurl=https%3A%2F%2Fwww.iconspedia.com%2Ficon%2Famazon-icon-47527.html&docid=q8rHnd-2NjaE1M&tbnid=_zuBIwta5LyQ_M%3A&vet=10ahUKEwid8Mqm9-3eAhVFKewKHbodAU8QMwhrKAIwAg..i&w=256&h=256&client=firefox-b&bih=966&biw=1920&q=amazon%20icon&ved=0ahUKEwid8Mqm9-3eAhVFKewKHbodAU8QMwhrKAIwAg&iact=mrc&uact=8

**Comment by skyfrk** [comment]
Proposed fix in develop branch @TheKrex
